### PR TITLE
Completed Chapters 4 and 5

### PR DESCRIPTION
**Pull request by sameeMushtak**
It looks like someone else got to chapter 5 before me, so there might be some issues with merging. Please let me know if there is anything I should do on my end for this pull request.

### CODE REVIEW

**Comment by opportunum** [comment]
Whoops, that was my commit, sorry about that, maybe put mine as 'alternative solution' if it will be easier to merge for now? I'll let future contributors combine them

**Comment by sameeMushtak** [comment]
Thanks for the suggestion @opportunum . I'm pretty new to Github so I wasn't sure of the best way to handle that. Since our solutions are pretty similar, I just combined most of our solutions and added alternative solutions where there were significant differences.

**Review by philip-healy — APPROVED** [review]

**Comment by philip-healy** [comment]
Awesome work @sameeMushtak, thank you so much

**Comment by opportunum** [comment]
Just checking to prevent duplicate work, anyone planning to do chapter 9?

**Comment by sameeMushtak** [comment]
I'm working on Chapter 3 right now. I haven't touched Chapter 9 yet.

**Comment by opportunum** [comment]
Alright I'll do chapter 9

**Pull request merged**
